exports.EVENT = {
    START: 'start',
    FIND_METHOD_LIKE: 'find_method_like',
    FIND_PARAM_WORD: 'find_param_word',
    FIND_RETURN_WORD: 'find_return_word',
    FIND_RELATIVE_WORD: 'find_relative_word',
    FIND_CONSTRUCTOR_WORD: 'find_constructor_word',
    FIND_PLAIN_TEXT: 'find_plain_text',
    OPEN_H: 'open_h',
    OPEN_P: 'open_p',
    CLOSE_P: 'close_p',
    OPEN_TABLE: 'open_table',
    CLOSE_TABLE: 'close_table',
    OPEN_TBODY: 'open_tbody',
    OPEN_TR: 'open_tr',
    CLOSE_TR: 'close_tr',
    OPEN_TD: 'open_td',
    CLOSE_TD: 'close_td',
    OPEN_CODE: 'open_code',
};
